dist: trusty
sudo: false

language: cpp
compiler: gcc

#before_script:
  #- git clone https://github.com/cpputest/cpputest.git
  #- cd cpputest
  #- git checkout v3.8
  #- cmake CMakeLists.txt
  #- make

addons:
  apt:
    packages:
    - cpputest


# Build steps
script:
  - mkdir build
  - cd build
  - cmake -DENABLE_TEST=ON ..
  - make
  - make test
