dist: trusty
sudo: false

language: cpp
compiler: gcc

before_script:
  # apt install
  - sudo apt-get update
  - sudo apt-get install -y libserial-dev
  
  # lib boost
  - sudo add-apt-repository -y ppa:mhier/libboost-latest
  - sudo apt-get update
  - sudo apt-get install -y libboost1.68-dev
  
  # cpputest
  - wget https://github.com/cpputest/cpputest/releases/download/v3.8/cpputest-3.8.tar.gz -O /tmp/cpputest.tar.gz
  - tar -xzvf /tmp/cpputest.tar.gz -C /tmp
  - cd /tmp/cpputest-* && ./configure --prefix=/tmp/cpputest-build && make && make install
  
  # knxtinyserial
  - wget https://github.com/giursino/knxtinyserial/archive/v1.1.0.tar.gz -O /tmp/knxtinyserial.tar.gz
  - tar -xzvf /tmp/knxtinyserial.tar.gz -C /tmp
  - cd /tmp/knxtinyserial-* && mkdir build && cd build
  - cmake .. && make && sudo make install


# Build steps
script:
  - cd $TRAVIS_BUILD_DIR && mkdir build && cd build
  - cmake -DENABLE_TEST=ON -DCPPUTEST_PATH=/tmp/cpputest-build ..
  - make
