dist: trusty
sudo: false

language: cpp
compiler: gcc

before_script:
  - wget https://github.com/cpputest/cpputest/releases/download/v3.8/cpputest-3.8.tar.gz -O /tmp/cpputest.tar.gz
  - tar -xzvf /tmp/cpputest.tar.gz -C /tmp
  - cd /tmp/cpputest-* && ./configure --prefix=/tmp/cpputest-build && make && make install && cd -
  - export CPPUTEST_HOME=/tmp/cpputest-build


# Build steps
script:
  - mkdir build
  - cd build
  - ls /tmp/cpputest-build
  - ls $CPPUTEST_HOME/lib
  - cmake -DENABLE_TEST=ON ..
  - make
  - make test
